name: Blog Post Proposal
description: Submit an idea to write for our developer blog
assignees: phazonoverload
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit an idea for our developer blog. Please wait for us to approve it before you start.
  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: Give us as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: key-objectives
    attributes:
      label: What are the key takeaways from your post?
      description: Provide they key things the reader will learn. Even if you're proposing an end-to-end project, think about what skills you're teaching that will be more-widely applicable. 
    validations:
      required: true
    validations:
      required: true
  - type: input
    id: country
    attributes:
      label: Country of residence
      description: Being a US-based company, there are some countries we just can't work with. Asking this question upfront allows us to identify this before anyone spends time writing.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms & Conditions
      options:
        - label: You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion. 
          required: true
        - label: You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished). 
          required: true
        - label: You understand that you will require a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671).
          required: true
        - label: You understand that you need to set up a Directus project by either running locally, self-hosting, or using Directus Cloud, but being a guest author does not entitle you to extended trials or free credit.
          required: true
        - label: You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
          required: true
        - label: You are aged 18 or over.
          required: true
